server:
  port: 8080
spring:
  application:
    name: ${INSTANCE_NAME:gateway-service}
  config:
    import:
      - optional:file:${CONFIGS_PATH:configs}/discovery-client.yaml
      - optional:file:${CONFIGS_PATH:configs}/actuator.yaml
      - optional:file:${CONFIGS_PATH:configs}/logging.yaml
      - optional:file:${CONFIGS_PATH:configs}/gateway.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:9090/realms/common-microservices}
          audiences: ${AUDIENCES:common-microservices}